delete specific backup
nicumaxian/db-backup pull request #17
Opened 2021-11-04 21:57 UTC by andrianboscanean

2021-11-05 11:12 UTC, nicumaxian requested changes

2021-11-05 11:12 UTC, nicumaxian commented on commands/backup.go
> +				Name:        "name",
can we add autocomplet?

2021-11-05 11:12 UTC, nicumaxian commented on commands/backup.go
> +		Description: "Delete existing backup file(s)",
i see only one operation is supported at once. you can use StringArray flag or only once file per operation.

2021-11-05 11:12 UTC, nicumaxian commented on commands/backup.go
> +				return err
add spinner.error to inform user about failure

2021-11-05 11:12 UTC, nicumaxian commented on commands/backup.go
> +			s.Stop()
s.success

2021-11-05 12:53 UTC, andrianboscanean commented on commands/backup.go
> +				Name:        "name",
we'll think a way,

2021-11-08 08:50 UTC, nicumaxian approved these changes

2021-11-08 12:19 UTC, merged